FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements-worker.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-worker.txt

COPY . .

CMD ["worker.handler"]
